version: "2.2"

services:
  license:
    image: age-license:${LICENSE_MANAGER_VERSION:-2025.0}
    build:
      context: .
      dockerfile: license/Dockerfile.license
      args:
        LICENSE_MANAGER_VERSION: ${LICENSE_MANAGER_VERSION:-2025.0}
    hostname: license.age-docker-cluster_default
    container_name: age-license
    expose:
      - "6200"
#    volumes:
#      - ./age.dat:/license/age.dat 
    mac_address: de:59:34:6f:b6:98

  head:
    image: age:${AGE_VERSION:-2025.1.0}
    build:
      context: .
      dockerfile: age/Dockerfile.age
      args: 
        AGE_VERSION: ${AGE_VERSION:-2025.1.0}
    command: ["head-node"]
    container_name: head 
    hostname: head.age-docker-cluster_default
    privileged: true 
    volumes:
      - opt_age:/opt/age
      - home_rstudio:/home/rstudio
      - home_ageadmin:/home/ageadmin
    expose:
      - "6444"
      - "6445"
    depends_on:
      - "license"

  c1:
    image: age:${AGE_VERSION:-2025.1.0} 
    build:
      context: .
      dockerfile: age/Dockerfile.age
      args: 
        AGE_VERSION: ${AGE_VERSION:-2025.1.0}
    command: ["compute-node"]
    hostname: c1.age-docker-cluster_default
    container_name: c1
    privileged: true 
    volumes:
      - opt_age:/opt/age 
      - home_rstudio:/home/rstudio
      - home_ageadmin:/home/ageadmin
      - opt_r:/opt/R
      - etc_rstudio:/etc/rstudio
      - usr_lib_rstudio:/usr/lib/rstudio-server
      - shared_storage:/opt/rstudio/shared
    expose:
      - "6444"
    depends_on:
      - "head"

  c2:
    image: age:${AGE_VERSION:-2025.1.0}
    build:
      context: .
      dockerfile: age/Dockerfile.age
      args: 
        AGE_VERSION: ${AGE_VERSION:-2025.1.0}
    command: ["compute-node"]
    hostname: c2.age-docker-cluster_default
    container_name: c2
    privileged: true
    volumes:
      - opt_age:/opt/age
      - home_rstudio:/home/rstudio
      - home_ageadmin:/home/ageadmin
      - opt_r:/opt/R
      - etc_rstudio:/etc/rstudio
      - usr_lib_rstudio:/usr/lib/rstudio-server
      - shared_storage:/opt/rstudio/shared
    expose:
      - "6444"
    depends_on:
      - "head"

  rsw:
    build:
      context: . 
      dockerfile: rsw/Dockerfile.rsw
      args:
        AGE_VERSION: ${AGE_VERSION:-2025.1.0}
        PWB_VERSION: ${PWB_VERSION:-2025.05.0-496.pro5}
    image: rsw:${PWB_VERSION:-2025.05.0-496.pro5}-${AGE_VERSION:-2025.1.0}
    command: ["rsw"]
    hostname: rsw.age-docker-cluster_default
    container_name: rsw
    privileged: true
    environment:
      PWB_LICENSE: ${PWB_LICENSE}
    volumes:
      - opt_age:/opt/age
      - home_rstudio:/home/rstudio
      - home_ageadmin:/home/ageadmin
      - opt_r:/opt/R
      - etc_rstudio:/etc/rstudio
      - usr_lib_rstudio:/usr/lib/rstudio-server
      - shared_storage:/opt/rstudio/shared
    ports:
      - "8787:8787"
    depends_on:
      - "head"
      - "c1"
      - "c2"

volumes:
  opt_age:
  home_ageadmin:
  home_rstudio:
  opt_r:
  etc_rstudio:
  usr_lib_rstudio:
  shared_storage:
