FROM ubuntu:noble

ARG LICENSE_MANAGER_VERSION=""    
ENV LIC=${LICENSE_MANAGER_VERSION}

COPY license/altair_licensing_${LICENSE_MANAGER_VERSION}.linux_x64.bin .

RUN bash altair_licensing_${LICENSE_MANAGER_VERSION}.linux_x64.bin -i silent && rm -f altair_licensing_${LICENSE_MANAGER_VERSION}.linux_x64.bin

COPY license/start-lic.sh .

RUN mkdir -p /license 
COPY age.dat /license

ENTRYPOINT ./start-lic.sh $LIC

